name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # roda todos os dias à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Clean dist folder
        run: rm -rf dist

      - uses: Platane/snk@v3
        with:
          github_user_name: ruigabriel1
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/tech-snake.gif?color_snake=#00fff7&color_dots=#0f2027,#2c5364,#00fff7,#ff00ea,#00ff85,#fffc00,#00fffc,#ff0066

      - name: Commit animation files
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: 'Generated snake animation'
          add: 'dist/*'