name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # roda todos os dias à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: ruigabriel1

          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Checkout repo
        uses: actions/checkout@v4   # ← ESSA LINHA É ESSENCIAL

      - name: Commit animation files
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: 'Generated snake animation'
          add: 'dist/*'
